### ISSUE TITLE
How to run jobs in a redis connection queue?

### ISSUE THREAD

**Issue by gregorip02** [brefphp/laravel-bridge#53]
I am currently using ElastiCache with redis as the driver for the queues. 

Based on your example posted at https://github.com/brefphp/examples/blob/master/Laravel/queues/worker.php I see that only one LaravelSqsHandler class is available, I am wondering if it is possible to process the jobs using LaravelRedisHandler or something like that.

**Comment by deleugpn** [comment]
That won't be "serverless" as you'll need a worker running 24/7 constantly hitting redis to see if there are available jobs. AWS Lambda isn't a good fit for this. What makes SQS natively supported is the fact that AWS provides a way to attach SQS to Lambda so that Lambda gets triggered automatically everytime a new message arrives.

**Comment by gregorip02** [comment]
Oh, I didn't know about native SQS support with lambda. In this case I will try to change my driver to SQS but I am afraid that I will have problems due to the short delay times.

Thanks
